"""empty message

Revision ID: 433068459ae3
Revises: f6afc3263d74
Create Date: 2025-03-05 18:10:16.059474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433068459ae3'
down_revision: Union[str, None] = 'f6afc3263d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
                    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('cabinet', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('position_at_work', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('computer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('work_group', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position_at_work', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('computer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('registration',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
