"""empty message

Revision ID: f45d4df4908a
Revises: 5f31e2dc6276
Create Date: 2025-02-20 15:32:15.973763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45d4df4908a'
down_revision: Union[str, None] = '5f31e2dc6276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position_at_work', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('computer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
